var memory = require('./memory.js')
var alloc = memory.cnst
var data = memory.data
var ads = memory.ads
var one = alloc(3)
data[one] = 0 // type integer
var idx = ads[one]
data[idx] = 1 // size one
var idx = ads[idx]
data[idx] = 1
module.exports = one
